In [1]:
import pandas as pd
import networkx as nx

path = 'Data/'

In [2]:
import pickle5 as pickle
import time

In [3]:
df = pd.read_parquet('{}file-name_query03-05.parquet'.format(path))
df

,Unnamed: 0,doi,bioActivity,collectionSpecie,collectionSite,collectionType,molType,molecularMass,monoisotropicMass,cLogP,tpsa,numberOfLipinskiViolations,numberOfH_bondAcceptors,numberOfH_bondDonors,numberOfRotableBonds,molecularVolume,smile,name,file_name
0,0,10.1016/j.biortech.2010.01.041,Inhibition of Protease,Piper crassinervium (Piperaceae),Araraquara/SP,Biotransformation Product,http://nubbe.db/AromaticDerivative,"290,354187","290,1517944","4,660999775","66,76100159",0.0,4.0,2.0,7.0,"282,9689941",O=C(OC/C=C(C)/CC/C=C(C)/C)C1=CC(O)=C(O)C=C1,"3,4-dihydroxybenzoic acid geranyl ester",10.1016@j.biortech.2010.01.041.pdf
1,0,10.1016/j.biortech.2010.01.041,Inhibition of Protease,Piper crassinervium (Piperaceae),Araraquara/SP,Biotransformation Product,http://nubbe.db/AromaticDerivative,"290,354187","290,1517944","4,660999775","66,76100159",0.0,4.0,2.0,7.0,"282,9689941",O=C(OC/C=C(C)/CC/C=C(C)/C)C1=CC(O)=C(O)C=C1,"3,4-dihydroxybenzoic acid geranyl ester",10.1016@j.biortech.2010.01.041.pdf
2,0,10.1016/j.biortech.2010.01.041,Inhibition of Protease,Piper crassinervium (Piperaceae),Araraquara/SP,Biotransformation Product,http://nubbe.db/AromaticDerivative,"290,354187","290,1517944","4,660999775","66,76100159",0.0,4.0,2.0,7.0,"282,9689941",O=C(OC/C=C(C)/CC/C=C(C)/C)C1=CC(O)=C(O)C=C1,"3,4-dihydroxybenzoic acid geranyl ester",10.1016@j.biortech.2010.01.041.pdf
3,0,10.1016/j.biortech.2010.01.041,Inhibition of Protease,Piper crassinervium (Piperaceae),Araraquara/SP,Biotransformation Product,http://nubbe.db/AromaticDerivative,"290,354187","290,1517944","4,660999775","66,76100159",0.0,4.0,2.0,7.0,"282,9689941",O=C(OC/C=C(C)/CC/C=C(C)/C)C1=CC(O)=C(O)C=C1,"3,4-dihydroxybenzoic acid geranyl ester",10.1016@j.biortech.2010.01.041.pdf
4,0,10.1016/j.biortech.2010.01.041,Inhibition of Protease,Piper crassinervium (Piperaceae),Araraquara/SP,Biotransformation Product,http://nubbe.db/AromaticDerivative,"290,354187","290,1517944","4,660999775","66,76100159",0.0,4.0,2.0,7.0,"282,9689941",O=C(OC/C=C(C)/CC/C=C(C)/C)C1=CC(O)=C(O)C=C1,"3,4-dihydroxybenzoic acid geranyl ester",10.1016@j.biortech.2010.01.041.pdf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11615,2386,10.1016/S0031-9422(00)94671-5,,,,,,,,,,,,,,,,,10.1016@S0031-9422(00)94671-5.pdf
11616,2387,10.1016/S0031-9422(00)80444-6,,,,,,,,,,,,,,,,,10.1016@S0031-9422(00)80444-6.pdf
11617,2388,10.1021/np50032a021,,,,,,,,,,,,,,,,,10.1021@np50032a021.pdf
11618,2389,10.1016/S0031-9422(00)83467-6,,,,,,,,,,,,,,,,,10.1016@S0031-9422(00)83467-6.pdf
11619,2390,10.1016/0031-9422(80)83208-0,,,,,,,,,,,,,,,,,10.1016@0031-9422(80)83208-0.pdf

In [4]:
texts_df = pd.read_parquet('{}topics03-05.parquet'.format(path))
texts_df

,doi,file_name,text,phrases,topics
0,10.1016/j.biortech.2010.01.041,10.1016@j.biortech.2010.01.041.pdf,Geranylation of benzoic acid derivatives by en...,[Geranylation of benzoic acid derivatives by e...,"[128, 132, 7, 13, 36, 42, 55, 79, 84, 91, 117,..."
1,10.1590/S0100-40422010000200017,10.1590@S0100-40422010000200017.pdf,"Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Arti...","[Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Art...","[19, 29, 116, 125]"
2,10.1590/S0103-50532006000500017,10.1590@S0103-50532006000500017.pdf,"J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934, ...","[J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934,...","[3, 13, 145, 144, 36, 42, 54, 56, 124, 125]"
3,10.1002/pca.818,10.1002@pca.818.pdf,FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM CR...,[FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM C...,"[135, 11, 13, 14, 141, 46, 65, 81, 116, 120, 1..."
4,10.1002/ps.478,10.1002@ps.478.pdf,Biological activity of astilbin from ���������...,[Biological activity of astilbin from ��������...,"[1, 131, 129, 7, 8, 137, 11, 140, 142, 16, 144..."
...,...,...,...,...,...
381,10.1016/S0031-9422(00)94671-5,10.1016@S0031-9422(00)94671-5.pdf,"Short Reports 1671 Dichrographe Mark III, R....","[Short Reports 1671 Dichrographe Mark III, R...","[129, 141, 84, 103]"
382,10.1016/S0031-9422(00)80444-6,10.1016@S0031-9422(00)80444-6.pdf,"Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296,...","[Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296...","[139, 145, 144, 36, 40, 42, 54, 56]"
383,10.1021/np50032a021,10.1021@np50032a021.pdf,Journal of Natural Products Vol. 47. No. 2. p...,[Journal of Natural Products Vol. 47. No. 2. ...,"[79, 103]"
384,10.1016/S0031-9422(00)83467-6,10.1016@S0031-9422(00)83467-6.pdf,"Phytockmistry, Vol. 23, No. 8, pp. 1677-1679,...","[Phytockmistry, Vol. 23, No. 8, pp. 1677-1679...","[135, 145, 19, 36, 83, 103, 124]"
385,10.1016/0031-9422(80)83208-0,10.1016@0031-9422(80)83208-0.pdf,"Phytochemistry, 1980, Vol. 19, pp. 474-476. © ...","[Phytochemistry, 1980, Vol. 19, pp. 474-476. ©...","[145, 17, 20, 31, 45, 52, 60, 80, 84, 97, 125]"

In [5]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

def create_phrases_from_sentences(text):
    # Tokenize text into sentences
    sentences = sent_tokenize(text)
    
    phrases = []
    current_phrase = []
    current_length = 0
    
    for sentence in sentences:
        sentence_length = len(sentence)
        
        # If single sentence exceeds 512, keep it as a whole phrase
        if sentence_length > 512:
            if current_phrase:  # Store any accumulated phrases first
                phrases.append(' '.join(current_phrase))
                current_phrase = []
                current_length = 0
            phrases.append(sentence)
            continue
            
        # Check if adding this sentence would exceed 512 characters
        if current_length + sentence_length + 1 <= 512:  # +1 for space
            current_phrase.append(sentence)
            current_length += sentence_length + 1
        else:
            # Store current phrase and start new one
            if current_phrase:
                phrases.append(' '.join(current_phrase))
            current_phrase = [sentence]
            current_length = sentence_length
    
    # Add any remaining phrases
    if current_phrase:
        phrases.append(' '.join(current_phrase))
    
    return phrases

# Apply the function to create phrases_2 column
texts_df['phrases_2'] = texts_df['text'].apply(create_phrases_from_sentences)
texts_df

[nltk_data] Downloading package punkt to /home/dfsbharath/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

,doi,file_name,text,phrases,topics,phrases_2
0,10.1016/j.biortech.2010.01.041,10.1016@j.biortech.2010.01.041.pdf,Geranylation of benzoic acid derivatives by en...,[Geranylation of benzoic acid derivatives by e...,"[128, 132, 7, 13, 36, 42, 55, 79, 84, 91, 117,...",[Geranylation of benzoic acid derivatives by e...
1,10.1590/S0100-40422010000200017,10.1590@S0100-40422010000200017.pdf,"Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Arti...","[Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Art...","[19, 29, 116, 125]","[Quim. Nova, Vol. 33, No., 2, 321-323, 2010 Ar..."
2,10.1590/S0103-50532006000500017,10.1590@S0103-50532006000500017.pdf,"J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934, ...","[J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934,...","[3, 13, 145, 144, 36, 42, 54, 56, 124, 125]","[J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934,..."
3,10.1002/pca.818,10.1002@pca.818.pdf,FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM CR...,[FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM C...,"[135, 11, 13, 14, 141, 46, 65, 81, 116, 120, 1...",[FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM C...
4,10.1002/ps.478,10.1002@ps.478.pdf,Biological activity of astilbin from ���������...,[Biological activity of astilbin from ��������...,"[1, 131, 129, 7, 8, 137, 11, 140, 142, 16, 144...",[Biological activity of astilbin from ��������...
...,...,...,...,...,...,...
381,10.1016/S0031-9422(00)94671-5,10.1016@S0031-9422(00)94671-5.pdf,"Short Reports 1671 Dichrographe Mark III, R....","[Short Reports 1671 Dichrographe Mark III, R...","[129, 141, 84, 103]","[Short Reports 1671 Dichrographe Mark III, R..."
382,10.1016/S0031-9422(00)80444-6,10.1016@S0031-9422(00)80444-6.pdf,"Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296,...","[Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296...","[139, 145, 144, 36, 40, 42, 54, 56]","[Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296..."
383,10.1021/np50032a021,10.1021@np50032a021.pdf,Journal of Natural Products Vol. 47. No. 2. p...,[Journal of Natural Products Vol. 47. No. 2. ...,"[79, 103]",[Journal of Natural Products Vol. 47. No. 2. ...
384,10.1016/S0031-9422(00)83467-6,10.1016@S0031-9422(00)83467-6.pdf,"Phytockmistry, Vol. 23, No. 8, pp. 1677-1679,...","[Phytockmistry, Vol. 23, No. 8, pp. 1677-1679...","[135, 145, 19, 36, 83, 103, 124]","[Phytockmistry, Vol. 23, No. 8, pp. 1677-1679..."
385,10.1016/0031-9422(80)83208-0,10.1016@0031-9422(80)83208-0.pdf,"Phytochemistry, 1980, Vol. 19, pp. 474-476. © ...","[Phytochemistry, 1980, Vol. 19, pp. 474-476. ©...","[145, 17, 20, 31, 45, 52, 60, 80, 84, 97, 125]","[Phytochemistry, 1980, Vol. 19, pp. 474-476. ©..."

In [6]:
from sentence_transformers import SentenceTransformer, LoggingHandler
import numpy as np
from tqdm.notebook import tqdm
import logging

#### Just some code to print debug information to stdout
np.set_printoptions(threshold=100)

logging.basicConfig(format='%(asctime)s - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S',
                    level=logging.INFO,
                    handlers=[LoggingHandler()])

# Load Sentence model (based on BERT) from URL
model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v2')

def model_encode(model):
    embeddings = []
    for _, phrases in tqdm(texts_df['phrases'].items()):
        embedding = np.zeros(512)
        for phrase in phrases:
            embedding += model.encode(phrase, show_progress_bar=False)
        embeddings.append(embedding)
    return embeddings

texts_df['embedding'] = model_encode(model)
texts_df

2026-04-22 19:28:10 - Load pretrained SentenceTransformer: sentence-transformers/distiluse-base-multilingual-cased-v2
2026-04-22 19:28:12 - Use pytorch device: cuda

0it [00:00, ?it/s]

,doi,file_name,text,phrases,topics,phrases_2,embedding
0,10.1016/j.biortech.2010.01.041,10.1016@j.biortech.2010.01.041.pdf,Geranylation of benzoic acid derivatives by en...,[Geranylation of benzoic acid derivatives by e...,"[128, 132, 7, 13, 36, 42, 55, 79, 84, 91, 117,...",[Geranylation of benzoic acid derivatives by e...,"[-0.8950120258668903, 0.6137961038039066, 0.44..."
1,10.1590/S0100-40422010000200017,10.1590@S0100-40422010000200017.pdf,"Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Arti...","[Quim. Nova, Vol. 33, No. 2, 321-323, 2010 Art...","[19, 29, 116, 125]","[Quim. Nova, Vol. 33, No., 2, 321-323, 2010 Ar...","[0.0405009975656867, 0.44275646680034697, -0.0..."
2,10.1590/S0103-50532006000500017,10.1590@S0103-50532006000500017.pdf,"J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934, ...","[J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934,...","[3, 13, 145, 144, 36, 42, 54, 56, 124, 125]","[J. Braz. Chem. Soc., Vol. 17, No. 5, 929-934,...","[-0.31248260155553, 0.4514679341809824, -0.311..."
3,10.1002/pca.818,10.1002@pca.818.pdf,FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM CR...,[FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM C...,"[135, 11, 13, 14, 141, 46, 65, 81, 116, 120, 1...",[FLAVONOID GLYCOSIDES AND STYRYLPYRONES FROM C...,"[-0.13642807520227507, 0.9625891325995326, -0...."
4,10.1002/ps.478,10.1002@ps.478.pdf,Biological activity of astilbin from ���������...,[Biological activity of astilbin from ��������...,"[1, 131, 129, 7, 8, 137, 11, 140, 142, 16, 144...",[Biological activity of astilbin from ��������...,"[0.3284127317601815, -0.26284066238440573, -1...."
...,...,...,...,...,...,...,...
381,10.1016/S0031-9422(00)94671-5,10.1016@S0031-9422(00)94671-5.pdf,"Short Reports 1671 Dichrographe Mark III, R....","[Short Reports 1671 Dichrographe Mark III, R...","[129, 141, 84, 103]","[Short Reports 1671 Dichrographe Mark III, R...","[-0.21970843500457704, 0.33494950411841273, 0...."
382,10.1016/S0031-9422(00)80444-6,10.1016@S0031-9422(00)80444-6.pdf,"Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296,...","[Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296...","[139, 145, 144, 36, 40, 42, 54, 56]","[Phytochemrstry, Vol. 23, No 6, pp. 1X33-1296...","[-0.21785177156561986, 0.9152516985777766, -0...."
383,10.1021/np50032a021,10.1021@np50032a021.pdf,Journal of Natural Products Vol. 47. No. 2. p...,[Journal of Natural Products Vol. 47. No. 2. ...,"[79, 103]",[Journal of Natural Products Vol. 47. No. 2. ...,"[-0.30958136823028326, 0.12105274572968483, -0..."
384,10.1016/S0031-9422(00)83467-6,10.1016@S0031-9422(00)83467-6.pdf,"Phytockmistry, Vol. 23, No. 8, pp. 1677-1679,...","[Phytockmistry, Vol. 23, No. 8, pp. 1677-1679...","[135, 145, 19, 36, 83, 103, 124]","[Phytockmistry, Vol. 23, No. 8, pp. 1677-1679...","[-0.2592933098785579, 0.36754319537431, -0.222..."
385,10.1016/0031-9422(80)83208-0,10.1016@0031-9422(80)83208-0.pdf,"Phytochemistry, 1980, Vol. 19, pp. 474-476. © ...","[Phytochemistry, 1980, Vol. 19, pp. 474-476. ©...","[145, 17, 20, 31, 45, 52, 60, 80, 84, 97, 125]","[Phytochemistry, 1980, Vol. 19, pp. 474-476. ©...","[-0.48299783864058554, 0.4926578173181042, -0...."

In [7]:
texts_df.to_parquet('{}topics_embeddings.parquet'.format(path))

In [8]:
import pandas as pd
import numpy as np
import re






def find_element_positions(phrase, element):
    """Find character and word positions of an element in a phrase."""
    if not isinstance(element, str) or pd.isna(element) or not element.strip():
        return None
    
    # Convert both to lowercase for case-insensitive matching
    phrase_lower = phrase.lower()
    element_lower = element.lower()
    
    # Find character position
    char_pos = phrase_lower.find(element_lower)
    if char_pos == -1:
        return None
        
    # Find word position
    words = phrase[:char_pos].split()
    start_word_pos = len(words)
    end_word_pos = start_word_pos + len(element_lower.split())
    

    return {
        'surface_char_pos': np.array([char_pos, char_pos + len(element_lower)]),
        'surface_form': element.lower(),
        'surface_word_pos': np.array([start_word_pos, end_word_pos]),
        'types': np.array([], dtype=object),
        'uri': element.lower()
    }

def process_entities(df, texts_df):
    # Merge the dataframes on doi
    merged_df = pd.merge(texts_df, df, on='doi', how='left')
    
    # Columns to check for entities
    entity_columns = ['bioActivity', 'collectionSpecie', 'collectionSite', 
                     'collectionType', 'name']
    
    data = []
    data_2 = []
    
    # Global counter for unique phrase IDs
    global_phrase_idx = 0
    
    # Iterate through each row
    for idx, row in merged_df.iterrows():
        if not isinstance(row['phrases_2'], list):
            continue
            
        # Process each phrase
        for phrase in row['phrases_2']:
            if not isinstance(phrase, str):
                continue
                
            phrase = re.sub("(\\d|\\W)+"," ",phrase)
            phrase = phrase.strip()

            data_2.append({
                'label': global_phrase_idx,
                'text_a': phrase.lower()
            })
                
            # Check each entity column
            for col in entity_columns:
                if col=='name':
                    if ';' in row[col]:
                        temp_element = row[col].split(';')
                        for te in temp_element:
                            te = re.sub("(\\d|\\W)+"," ",te)
                            te = te.strip()
                            positions = find_element_positions(phrase, te)

                    else:
                        element = row[col]
                        element = re.sub("(\\d|\\W)+"," ",element)
                        element = element.strip()
                        positions = find_element_positions(phrase, element)

                else:
                            
                    element = row[col]
                    element = re.sub("(\\d|\\W)+"," ",element)
                    element = element.strip()
                    positions = find_element_positions(phrase, element)
                
                if positions:
                    data.append({
                        'source_id': global_phrase_idx,
                        'entity_data': positions,
                        'uri': element.lower()
                    })
            
            # Increment the global counter after processing each phrase
            global_phrase_idx += 1
    
    return data, data_2

# Example usage:
data, data_2 = process_entities(df, texts_df)

In [9]:
data

[{'source_id': 0,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 2,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 18,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 67,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 114,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 115,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 116,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 132,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 181,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 228,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 229,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 230,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 246,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 295,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 342,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 343,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 344,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 360,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 409,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 456,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 457,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 458,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 474,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 523,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 570,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 571,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 572,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 588,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 637,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 684,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 685,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 686,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 702,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 751,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 798,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 799,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 800,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 816,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 865,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 912,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 913,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 914,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 930,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 979,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1026,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1027,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1028,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1044,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1093,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1140,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1141,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1142,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1158,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1207,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1254,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1255,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1256,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1272,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1321,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1368,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1369,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1370,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1386,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1435,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1482,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1483,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1484,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1500,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1549,
  'entity_data': {'surface_char_pos': array([28, 53]),
   'surface_form': 'biotransformation product',
   'surface_word_pos': array([4, 6]),
   'types': array([], dtype=object),
   'uri': 'biotransformation product'},
  'uri': 'biotransformation product'},
 {'source_id': 1596,
  'entity_data': {'surface_char_pos': array([68, 98]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([ 9, 12]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1597,
  'entity_data': {'surface_char_pos': array([ 0, 13]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([0, 2]),
   'types': array([], dtype=object),
   'uri': 'araraquara sp'},
  'uri': 'araraquara sp'},
 {'source_id': 1598,
  'entity_data': {'surface_char_pos': array([176, 206]),
   'surface_form': 'piper crassinervium piperaceae',
   'surface_word_pos': array([33, 36]),
   'types': array([], dtype=object),
   'uri': 'piper crassinervium piperaceae'},
  'uri': 'piper crassinervium piperaceae'},
 {'source_id': 1614,
  'entity_data': {'surface_char_pos': array([464, 477]),
   'surface_form': 'araraquara sp',
   'surface_word_pos': array([71, 73]),
   'types': array([], dtype=object),

In [10]:
data_2

[{'label': 0,
  'text_a': 'geranylation of benzoic acid derivatives by enzymatic extracts from piper crassinervium piperaceae silvia noelí lópez a adriana aparecida lopes a joão marcos batista jr a otávio flausino jr a vanderlan da silva bolzani a massuo jorge kato b maysa furlan a a nubbe núcleo de bioensaios biossíntese e ecoﬁsiologia de produtos naturais departamento de química orgânica instituto de química universidade estadual paulista unesp c p'},
 {'label': 1,
  'text_a': 'araraquara sp brazil b instituto de química universidade de são paulo usp av'},
 {'label': 2,
  'text_a': 'prof lineu prestes são paulo sp brazil a r t i c l e i n f o article history received july received in revised form january accepted january available online february keywords piper crassinervium piperaceae biotransformation geranylation a b s t r a c t the ability to carry out geranylations on aromatic substrates using enzymatic extracts from the leaves of piper crassinervium piperaceae was evaluated'},
 {'label': 3,
  'text_a': 'a literature analysis pointed out its importance as a source of prenylated bioactive molecules the screening performed on aromatic acceptors benzoic acids phenols and phenylpropanoids including geranyl diphosphate as prenyl donor showed the biotransfor mation of the dihydroxybenzoic acid by the crude extract and the p hydroxybenzoic acid by both the microsomal fraction and the crude extract after treating leaves with glucose'},
 {'label': 4,
  'text_a': 'the analysis of the products allowed the identiﬁcation of c and o geranylated derivatives and the protease subtilisin and pepsin inhibition performed on the o geranylated compounds showed weak inhibition electrophoretic proﬁles indicated the presence of bands spots among kda and pi which are compatible with pren yltransferases'},
 {'label': 5,
  'text_a': 'these ﬁndings show that p crassinervium could be considered as a source of extracts with geranyltransferase activity to perform biotransformations on aromatic substrates elsevier ltd all rights reserved introduction biotransformations are chemical reactions catalyzed by cells organs or enzymes they are different from biosynthesis where complex products are assembled from simple substrates by whole cells organs or organisms'},
 {'label': 6,
  'text_a': 'plant enzyme biocatalysts can be uti lized to introduce new structural motifs on existing drugs expect ing to improve their bioactivity pharmacokinetic proﬁle and also for the production of new drugs giri et al so far natural products bearing one or more prenyl groups have been isolated predominantly from higher plants'},
 {'label': 7,
  'text_a': 'these com pounds originated from several natural product classes often hold antimicrobial antioxidant anti inﬂammatory antiviral and anti cancer activities epifano et al since the prenylation of small aromatic molecules is a pivotal step in the biosynthesis of many natural products the access to prenylation reaction catalysts might represent an advantageous short cut to obtain prenylated aromatic compounds yazaki et al haagena et al'},
 {'label': 8,
  'text_a': 'aromatic geranyltransferases are a sub class of prenyltransfe rases that catalyzes c geranylations on several aromatic sub strates several examples of new aromatic prenyltransferases have been reported from bacteria as soluble monomeric biocata lysts with a relatively high promiscuity for aromatic substrates'},
 {'label': 9,
  'text_a': 'in spite of the lack of a full elucidation of substrate and regio speciﬁcity these enzymes were successfully employed to carry out either c or o prenylations of several compounds epifano et al in plants aromatic geranyltransferases are mem brane bound proteins showing a strict substrate speciﬁcity for the endogenous prenyl donor groups e g dmapp gpp etc'},
 {'label': 10,
  'text_a': 'although they may accept a variety of aromatic compounds as acceptors of the prenyl moieties yazaki et al kuzuyama et al there are few examples in which prenyltransferases have been isolated and characterized from plants mühlenweg et al therefore biotransformations using plant enzymatic extracts enriched in prenyltransferase activity could be used as an alternative to obtain either known or new bioactive compounds'},
 {'label': 11,
  'text_a': 'piperaceae family is a basal angiosperm family comprising more than species'},
 {'label': 12,
  'text_a': 'its species are chemically very rich and major classes of compounds described include phenylpropanoids orjala et al lignan neolignans parmar et al bene vides et al martins et al felippe et al pyrones singh aliphatic and aromatic amides alécio et al silva et al alkaloids dodson et al polyketides cheng et al benzoic acid derivatives bergamo et al morandim et al and chromenes lago et al morandim et al salazar et al'},
 {'label': 13,
  'text_a': 'belonging to this see front matter elsevier ltd all rights reserved doi j biortech corresponding author tel x fax e mail addresses maysaf iq unesp br maysaf reitoria unesp br m furlan these authors contributed equally to this work as second authors'},
 {'label': 14,
  'text_a': 'bioresource technology contents lists available at sciencedirect bioresource technology journal homepage www elsevier com locate biortech family piper is one of the most abundant genera with approxi mately species wanke et al piper crassinervium spe cies accumulates antifungal trypanocidal and antioxidant c geranylated metabolites derived from both benzoic acid and p hydroquinone danelutte et al yamaguchi et al lopes et al'},
 {'label': 15,
  'text_a': 'in spite of the knowledge on the chemical constituents and the biological potential of piperaceae species no comprehensive study has been made in order to survey such bioactive metabolites with in the members of the family here we present a compilation that points out to the impor tance of piper genus as a source of bioactive compounds and par ticularly of p crassinervium as an enzyme source to perform geranylations on aromatic substrates we report the biotransfor mation i e'},
 {'label': 16,
  'text_a': 'the geranylation of both the p hydroxybenzoic and dihydroxybenzoic acids carried out by the enzymatic extracts from the leaves of p crassinervium besides the full characterization of two products as geranyl ester derivatives in addition to the char acterization of one major product formed by biotransformation of the dihydroxybenzoic acid as a c geranylated derivative'},
 {'label': 17,
  'text_a': 'addi tionally the inhibitory activity on hiv like proteases was determined for the products as well as the electrophoretic charac terization of catalytically active protein fractions by using sds page and de methods literature survey and analysis piperaceae and activity were used as key words to perform a search in the available databases e g science direct and acs dat abases'},
 {'label': 18,
  'text_a': 'all the obtained information was uploaded in a table according to genus species type of compound and biological activ ity reported see the electronic annex in the online version of this article typical software excel microsoft corporation was used to analyse and plot the obtained information plant material fresh leaves of p crassinervium were collected from adults spec imens cultivated from seeds under greenhouse conditions at the institute of chemistry unesp araraquara sp brazil'},
 {'label': 19,
  'text_a': 'plant material was authenticated by dr guillermo paredes universidad pedro ruiz gallo peru and the voucher specimen kato was deposited at the herbarium of instituto de botânica são paulo sp brazil incubation into b d glucose of young leaves from p crassiner vium leaves freshly excised from an adult plant were placed sep arately in ml eppendorf tubes and each administrated ll from a solution of b d glucose in water at c for h berg amo et al'},
 {'label': 20,
  'text_a': 'synthesis and puriﬁcation of geranyl diphosphate gpp in a ml round bottom ﬂask mmol of geraniol was mixed with mmol of trichloroacetonitrile bis triethylammonium phos phate mmol in ml of acetonitrile was added drop wise to the mixture over a period of h at room temperature under con tinuous stirring cornforth and popják'},
 {'label': 21,
  'text_a': 'the mixture was fur ther stirred for h at room temperature and then the reaction was stopped by dilution with ml of ethyl ether followed by extraction with ml of nh oh m the basic solution was then re extracted with ml of ethyl ether and evapo rated under reduced pressure'},
 {'label': 22,
  'text_a': 'the gpp was puriﬁed by precipita tion in acetonitrile at c overnight compared with a commercial sample using tlc on cellulose isopropanol aque ous ammonia water and characterized by h c and p nmr h nmr mhz d o d h d j hz h t j hz h and h m h m ch s ch s ch s'},
 {'label': 23,
  'text_a': 'c nmr mhz d o d c c c c c c c c c and c p nmr h po mhz d o d p p'},
 {'label': 24,
  'text_a': 'synthesis puriﬁcation and characterization of the o geranyl derivatives of the dihydroxybenzoic acid to a stirred solution of the dihydroxibenzoic acid mmol in dry dmf ml anhydrous potassium carbonate mmol was added and the solution stirred for min at c under nitrogen atmosphere pisco et al geranyl bromide mmol was added drop wise and the resulting mixture was heated and stirred at the same temperature for h under nitrogen atmosphere'},
 {'label': 25,
  'text_a': 'the mixture was then poured into cold water ml added with of hoac and extracted with chcl ml and etoac ml the etoac layer was washed dried with na so and evaporated under reduced pressure and the residue was submitted to column chromatography silica gel mesh iso cratic elution with hex etoac yielding ﬁve fractions fraction was characterized as compound fraction as com pound and fraction as compound'},
 {'label': 26,
  'text_a': 'the puriﬁed products were characterized by h c nmr dept ghmbc ghmqc and esi ms fig table synthesis puriﬁcation and characterization of the o geranyl derivatives of the p hydroxybenzoic acid the p hydroxybenzoic acid mmol dissolved in ml of thf was added to a slurry of g of al o neutral in ether ml glü senkamp and büchi the solvent was evaporated and gera nyl bromide mmol in ether hexane was added'},
 {'label': 27,
  'text_a': 'after stirring during days al o was ﬁltered off and washed with hoac in etoac the combined organic layer was evaporated and the products were puriﬁed using column chromatography silica gel mesh gradient elution with hex hex etoac yielding fractions'},
 {'label': 28,
  'text_a': 'from fraction it was characterized the geranyl ester derivative whereas the geranyl ether derivative was puriﬁed from fraction by subsequent column chromatography silica gel mesh isocratic elution with hex etoac the puriﬁed products were characterized by h c nmr dept ghmbc ghmqc and esi ms table fig protein extraction leaves of p crassinervium were harvested from an adult speci men and maintained in liquid n'},
 {'label': 29,
  'text_a': 'the frozen leaves g were triturated in a mortar with addition of polyvinylpolypyrroli done pvpp mm dithiothreitol dtt and mm ethylenedi aminetetraacetic acid edta in ml of mm potassium phosphate kpi ph the homogenate was stirred slowly by min in ice bath ﬁltered on gauze and centrifuged at rpm for min to obtain the supernatant crude enzymatic extract which was then submitted to protein determination activity assay and electrophoretic analysis'},
 {'label': 30,
  'text_a': 'microsomal fraction the protocol was performed according to mühlenweg et al with minimal modiﬁcations the supernatant ml ob tained as described in section was subjected to ultracentrifuga s n lópez et al bioresource technology tion at rpm for h the resulting pellet was resuspended in ml of m tris hcl ph containing mm dtt m kcl and w v glycerol and stirred on ice for min'},
 {'label': 31,
  'text_a': 'the suspen sion was subjected to ultracentrifugation as described above the supernatant was discarded and the tube was carefully rinsed with m tris hcl ph the pellet was then resuspended in ml of m tris hcl ph containing mm dtt m kcl w v glycerol and mm cholamidopropyl dimethylammo nium hydroxy propanesulphonate chapso and stirred on ice for min'},
 {'label': 32,
  'text_a': 'the suspension was ultracentrifuged as described above and the desired proteins were recovered as supernatant which was passed through a sephadex g column cm long cm i d previously equilibrated with the m tris hcl ph containing mm chapso mm dtt and w v glycerol the eluate was submitted to protein determination activity assay and electrophoretic analysis'},
 {'label': 33,
  'text_a': 'protein determination the protein determination was performed by the bradford modiﬁed method using bovine serum albumin bsa as standard stoscheck detection of the geranyltransferase activity the reaction mixture ll containing mm kpi ph mm of precursors mm gpp mm mgcl or mncl and ll of the proteic extract was incubated under stirring for min at c the reaction was stopped with the addition of ll of m hcl and extracted with ll of etoac'},
 {'label': 34,
  'text_a': 'after vortex and centrifugation the organic layer was evaporated the residue dissolved in meoh ll and analysed by hplc uv using a phenomenex gemini column lm c å mm at a ﬂow rate of ml min an isocratic condition min con sisted of acetonitrile and aqueous hoac with detection at and nm injection volume ll'},
 {'label': 35,
  'text_a': 'for each reaction two negative controls which consisted of enzymatic extract buffer and precursor divalent cation gpp buffer were carried out simultaneously each experiment was performed in duplicate sodium dodecylsulphate polyacrylamide electrophoresis sds page the sds page was performed according to the supplier infor mation ge healthcare the polyacrylamide gels were stained with agno'},
 {'label': 36,
  'text_a': 'the relative molecular mass mr of denatured proteins was estimated using the labimage d software cali brated with low molecular weight standards phosphorylase b sericalbumin ovalbumin carbonic anhydrase and trypsin inhibi tor with and kda respectively two dimensional electrophoresis de the de with immobilized ph gradients ipg dalt was carried out according to the supplier information ge healthcare'},
 {'label': 37,
  'text_a': 'the ipg strips cm were rehydrated for h with sample pro teins previously treated with the clean up kit ge healthcare table h nmr data mhz j hz cdcl c nmr data mhz cdcl and ghmbc correlations observed for compounds o o o r r r r r h r r r h o r r r r h'},
 {'label': 38,
  'text_a': 'position h nmr c nmr ghmbc d d d coo d d d dd dd dd coo d d d coo tbr t t m m m m m m tbr t t s s s s s s s s s coo cooh n o'},
 {'label': 39,
  'text_a': 'n o oh n o n o oh n o n o note not observed from the correlations observed in ghmbc s n lópez et al bioresource technology in an immobiline drystrip reswelling tray first dimension iso electric focusing ief was carried out in an ettan ipgphor ii man ifold applying a manufacturer s standard protocol'},
 {'label': 40,
  'text_a': 'the second dimension was performed on a vertical cm poly acrylamide sds gel in a se ruby system ma gel and v each gel was stained with silver according to the silver staining protocol amersham biosciences inhibition of the protease activity reagents pepsin was from porcine gastric mucous'},
 {'label': 41,
  'text_a': 'recombinant type viii subtilisin carlsberg arg glu edans ser gln asn tyr pro ile val gln lys dabcyl arg ﬂuorogenic substrate edans dabcyl and dimethylsulphoxide dmso spectrophotometric grade were from sigma aldrich são paulo brazil protease activity assay the assays were performed in triplicate compounds were dis solved in dmso and diluted in m sodium phosphate ph for subtilisin and m sodium acetate ph for pepsin respec tively'},
 {'label': 42,
  'text_a': 'warfarin and dicoumarol were used as positive controls thaisrivongs et al pochet et al samples and stan dard inhibitors lg ml were pre incubated with subtilisin nm or pepsin nm for h and then transferred to a black opaque microplate to be tested the substrate edans dabcyl lm was prepared in the speciﬁc buffer for each protease in the control assay only protease and substrate were used'},
 {'label': 43,
  'text_a': 'proteases were prepared in the day of the experiment and the tests were per formed for each one separately readings were made using nm excitation and nm emission ﬁlters during min with min intervals at c hirata et al the ﬂuorescence intensity was used to calculate the of inhibition as follows i ¼ ½ðdfs dfpþ where dfs and dfp are the difference between the ﬁrst and last readings for the sample test and the control respectively'},
 {'label': 44,
  'text_a': 'fluorescence bioassay data were collected with a multidetec tion microplate reader synergy ht and analysed using the kc software bio tek instruments inc and microsoft windows xp results and discussion prenylation is a chemical or enzymatic addition of a hydropho bic side chain to an accepting molecule another terpenoid mole cule an aromatic compound a protein etc'},
 {'label': 45,
  'text_a': 'in particular the prenylation of aromatic secondary metabolites plays a critical role in the biosynthesis of a wide range of molecules exerting valuable pharmacological effects several examples can be found in phylo genetically different classes of living organisms from bacteria across mammals to plants epifano et al phytochemical investigations carried out on piper species have led to the isolation of many bioactive natural products'},
 {'label': 46,
  'text_a': 'the analy sis of the distribution of these bioactive compounds by genus type of compound and bioactivity in the piperaceae family was performed looking at particularly the importance of prenylated natural products within that universe the search was performed using piperaceae and activity as key words in the available web databases this search resulted in entries see the elec tronic annex in the online version of this article which were ana lysed and discussed here'},
 {'label': 47,
  'text_a': 'the analysis was performed considering the botanical classiﬁcation as provided in the publications regarding the distribution of bioactive compounds reported within genera a predominance of piper genus over peperomia genus was observed representing in spite of the large number of species belonging to peperomia genus about species ver sus from piper wanke et al it only contributes with of the total reports published'},
 {'label': 48,
  'text_a': 'such differences can be ac counted for the fact that piper species have been more exhaustively table h nmr data mhz j hz cdcl for compounds and c nmr data mhz cdcl and ghmbc correlations for compound o o o r r r r h r r h'},
 {'label': 49,
  'text_a': 'position compound compound h nmr c nmr ghmbc h nmr d coo d d d d d d coo d d coo d t tbr m m m m t tbr s s s s s s cooh n o'},
 {'label': 50,
  'text_a': 'oh n o note not observed oh oh o cooh oh o sarcorhachis ottonia pothomorphe p crassinervium fig distribution of piperaceae members considering the report of some biological activity for their isolated compounds'},
 {'label': 51,
  'text_a': 'the abundance of piper crassiner vium is highlighted and the structure of the geranylated bioactive compounds hydroxy e dimethyl oxo octadienyl benzoic acid and dihy droxy e dimethyl oxo octadienyl benzene is presented for details see the electronic annex s n lópez et al bioresource technology studied partially due to their wide occurrence and biomass avail ability fig electronic annex'},
 {'label': 52,

In [11]:
entities = pd.DataFrame(data)

In [12]:
texts = pd.DataFrame(data_2)

In [13]:
entities

,source_id,entity_data,uri
0,0,"{'surface_char_pos': [68, 98], 'surface_form':...",piper crassinervium piperaceae
1,1,"{'surface_char_pos': [0, 13], 'surface_form': ...",araraquara sp
2,2,"{'surface_char_pos': [176, 206], 'surface_form...",piper crassinervium piperaceae
3,18,"{'surface_char_pos': [464, 477], 'surface_form...",araraquara sp
4,67,"{'surface_char_pos': [28, 53], 'surface_form':...",biotransformation product
...,...,...,...
100346,684319,"{'surface_char_pos': [21, 33], 'surface_form':...",piperovatine
100347,684323,"{'surface_char_pos': [189, 201], 'surface_form...",piperovatine
100348,684341,"{'surface_char_pos': [289, 299], 'surface_form...",anesthetic
100349,684342,"{'surface_char_pos': [416, 428], 'surface_form...",piperovatine
100350,684353,"{'surface_char_pos': [291, 303], 'surface_form...",piperovatine

In [14]:
entities.to_parquet('../kims-bert/CODE/K-BERT/datasets/scholarly_dataset/scholarly__3000__train__entity_mapping_by_sentence.parquet')

In [15]:
texts.to_csv("../kims-bert/CODE/K-BERT/datasets/scholarly_dataset/scholarly__3000__train.tsv", sep="\t", index=False)

In [16]:
import pandas as pd
import pickle5 as pickle
from rdkit import Chem
from rdkit.Chem import Descriptors, Crippen

# Create lists to store the SPO triples
spo_triples = []

# Function to add triple if value exists
def add_triple_if_exists(subject, predicate, object_value):
    if pd.notna(object_value) and object_value != "":
        spo_triples.append(f"{subject}\t{predicate}\t{object_value}")

def classify_compound(smiles):
    """Classify compound based on RDKit analysis"""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None

        classifications = {}
        
        # Molecular weight class
        mw = Descriptors.MolWt(mol)
        if mw < 150:
            classifications['weight_class'] = 'small_molecule'
        elif mw < 300:
            classifications['weight_class'] = 'medium_molecule'
        elif mw < 600:
            classifications['weight_class'] = 'large_molecule'
        else:
            classifications['weight_class'] = 'very_large_molecule'

        # Lipinski's Rule of Five
        hbd = Descriptors.NumHDonors(mol)
        hba = Descriptors.NumHAcceptors(mol)
        logp = Crippen.MolLogP(mol)

        if mw <= 500 and hbd <= 5 and hba <= 10 and logp <= 5:
            classifications['drug_likeness'] = 'drug_like'
        else:
            classifications['drug_likeness'] = 'non_drug_like'

        # Aromaticity
        aromatic_atoms = sum(1 for atom in mol.GetAtoms() if atom.GetIsAromatic())
        aromatic_fraction = aromatic_atoms / mol.GetNumAtoms() if mol.GetNumAtoms() > 0 else 0

        if aromatic_fraction > 0.3:
            classifications['aromaticity'] = 'aromatic_rich'
        elif aromatic_fraction > 0:
            classifications['aromaticity'] = 'partially_aromatic'
        else:
            classifications['aromaticity'] = 'aliphatic'

        # Ring systems
        num_rings = len(Chem.GetSSSR(mol))
        if num_rings == 0:
            classifications['ring_type'] = 'acyclic'
        elif num_rings == 1:
            classifications['ring_type'] = 'monocyclic'
        elif num_rings <= 3:
            classifications['ring_type'] = 'polycyclic'
        else:
            classifications['ring_type'] = 'highly_polycyclic'

        return classifications
    except:
        return None

# Process each row in the DataFrame
for _, row in df.iterrows():
    doi = row['doi']

    row['bioActivity'] = re.sub("(\\d|\\W)+", " ", row['bioActivity'])
    row['collectionSpecie'] = re.sub("(\\d|\\W)+", " ", row['collectionSpecie'])
    row['collectionSite'] = re.sub("(\\d|\\W)+", " ", row['collectionSite'])
    row['collectionType'] = re.sub("(\\d|\\W)+", " ", row['collectionType'])

    # Clean and trim each field
    row['bioActivity'] = row['bioActivity'].strip()
    row['collectionSpecie'] = row['collectionSpecie'].strip()
    row['collectionSite'] = row['collectionSite'].strip()
    row['collectionType'] = row['collectionType'].strip()

    # Add triples for each specified relationship
    add_triple_if_exists(row['bioActivity'].lower(), "bioActivity", doi)
    add_triple_if_exists(row['collectionSpecie'].lower(), "collectionSpecie", doi)
    add_triple_if_exists(row['collectionSite'].lower(), "collectionSite", doi)
    add_triple_if_exists(row['collectionType'].lower(), "collectionType", doi)

    # Add triples for chemicals with RDKit enrichment
    if pd.notna(row['smile']) and row['smile'].strip():
        smiles = row['smile'].strip()
        chem_name = row['name'].lower()
        
        # Get RDKit classifications
        classifications = classify_compound(smiles)
        '''if classifications:
            for key, value in classifications.items():
                add_triple_if_exists(chem_name, f"rdkit:{key}", value)'''
        
        # Also add the name-doi relationship
        add_triple_if_exists(chem_name, "name", doi)
    
        
    if ';' in row['name']:
        temp = row['name'].split(';')
        for t in temp:
            t = re.sub("(\\d|\\W)+", " ", t)
            t = t.strip()
            add_triple_if_exists(t.lower(), "name", doi)
            if classifications:
                for key, value in classifications.items():
                    add_triple_if_exists(t.lower(), f"rdkit:{key}", value)
            
    else:
        row['name'] = re.sub("(\\d|\\W)+", " ", row['name'])
        row['name'] = row['name'].strip()
        add_triple_if_exists(row['name'].lower(), "name", doi)
        if classifications:
            for key, value in classifications.items():
                add_triple_if_exists(row['name'].lower(), f"rdkit:{key}", value)

# Write to .spo file
with open('../kims-bert/CODE/K-BERT/brain/kgs/KG_3cols.spo', 'w', encoding='utf-8') as f:
    f.write("sub\tpred\tobj\n")  # Header
    f.write('\n'.join(spo_triples))

print("Knowledge graph has been created in knowledge_graph.spo")

2026-04-22 19:32:37 - Enabling RDKit 2022.09.5 jupyter extensions
Knowledge graph has been created in knowledge_graph.spo